apiVersion: v1
kind: Pod
metadata:
  name: loyalty-games-app
  labels:
    app.kubernetes.io/name: loyalty-games-proxy
    component: loyaltygames-app
spec:
  containers:
  - name: loyaltygames-webapi
    image: loyaltygameregistry.azurecr.io/edgloyaltygamesapis:latest
    ports:
      - containerPort: 80
        name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: loyalty-games-app-service
spec:
  selector:
    app.kubernetes.io/name: loyalty-games-proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 8080
    targetPort: http-web-svc
  type: LoadBalancer