apiVersion: v1
kind: Service
metadata:
  name: loyalty-games-app
spec:
  containers:
    ports:
    - port: 8080
    protocol: TCP
    targetPort: 80
selector:
  app: loyaltygames-aks
  component: loyaltygames-app
  type: LoadBalancer