apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-games-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty-games-app
  template:
    metadata:
      labels:
        app: loyalty-games-app
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: loyalty-games-app
        image: loyaltygameregistry.azurecr.io/edgloyaltygamesapis:latest
        imagePullPolicy: Always        
        ports:
        - containerPort: 3000
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: loyalty-games-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: loyalty-games-app
  type: LoadBalancer